---
baseurl: ""
url: "https://www.eurogospodarka.com"

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - Gruntfile.js
  - package.json
  - package-lock.json
  - README*
  - node_modules
