#-------------------------------
# General Site Settings

title: Eurogospodarka
description: Pismo społeczno-gospodarcze
logo: eurogospodarka-logo-www-red-retina.png
email: redakcja@eurogospodarka.eu
phone: +48 574 662 644
address: ul. Zielna 39, 00-108 Warszawa

menu:
- {name: Wydanie on-line, link: 'https://eurogospodarka.eu/e-wydania/'}
- {name: Kontakt, link: '/kontakt/'}

google-analytics: 

#-------------------------------
# Hero Section

hero:
  hero-title: Pismo <br> społeczno-gospodarcze

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/eurogospodarka.miesiecznikdlawszystkich"}
- {icon: "ti-twitter", link: "https://twitter.com/eurogospodarka"}


# Issues Section
issues:
# 2012
  - title : "Eurogospodarka 01.2012"
    image : "assets/images/issues/012012.jpg"   
  - title : "Eurogospodarka 02.2012"
    image : "assets/images/issues/022012.png"   
  - title : "Eurogospodarka 04.2012"
    image : "assets/images/issues/042012.jpg"
  - title : "Eurogospodarka 05.2012"
    image : "assets/images/issues/052012.jpg"    
  - title : "Eurogospodarka 06.2012"
    image : "assets/images/issues/062012.jpg"   
  - title : "Eurogospodarka 07.2012"
    image : "assets/images/issues/072012.jpg"    
  - title : "Eurogospodarka 08.2012"
    image : "assets/images/issues/082012.jpg"   
  - title : "Eurogospodarka 09.2012"
    image : "assets/images/issues/092012.jpg"   
  - title : "Eurogospodarka 10.2012"
    image : "assets/images/issues/102012.jpg"   
  - title : "Eurogospodarka 11.2012"
    image : "assets/images/issues/112012.jpg"  
  - title : "Eurogospodarka 12.2012"
    image : "assets/images/issues/122012.jpg"
# 2013
  - title : "Eurogospodarka 01.2013"
    image : "assets/images/issues/012013.jpg"  
  - title : "Eurogospodarka 03.2013"
    image : "assets/images/issues/032013.jpg"    
  - title : "Eurogospodarka 04.2013"
    image : "assets/images/issues/042013.jpg"
  - title : "Eurogospodarka 05.2013"
    image : "assets/images/issues/052013.jpg"    
  - title : "Eurogospodarka 06.2013"
    image : "assets/images/issues/062013.jpg"   
  - title : "Eurogospodarka 07.2013"
    image : "assets/images/issues/072013.jpg"    
  - title : "Eurogospodarka 08.2013"
    image : "assets/images/issues/082013.jpg"   
  - title : "Eurogospodarka 09.2013"
    image : "assets/images/issues/092013.jpg"   
  - title : "Eurogospodarka 10.2013"
    image : "assets/images/issues/102013.jpg"   
  - title : "Eurogospodarka 11.2013"
    image : "assets/images/issues/112013.jpg"  
  - title : "Eurogospodarka 12.2013"
    image : "assets/images/issues/122013.jpg"
# 2014
  - title : "Eurogospodarka 01.2014"
    image : "assets/images/issues/012014.jpg" 
  - title : "Eurogospodarka 02.2014"
    image : "assets/images/issues/022014.jpg"    
  - title : "Eurogospodarka 03.2014"
    image : "assets/images/issues/032014.jpg"    
  - title : "Eurogospodarka 04.2014"
    image : "assets/images/issues/042014.jpg"
  - title : "Eurogospodarka 05.2014"
    image : "assets/images/issues/052014.png"    
  - title : "Eurogospodarka 06.2014"
    image : "assets/images/issues/062014.jpg"   
  - title : "Eurogospodarka 07.2014"
    image : "assets/images/issues/072014.jpg"    
  - title : "Eurogospodarka 08.2014"
    image : "assets/images/issues/082014.jpg"   
  - title : "Eurogospodarka 09.2014"
    image : "assets/images/issues/092014.jpg"   
  - title : "Eurogospodarka 10.2014"
    image : "assets/images/issues/102014.jpg"   
  - title : "Eurogospodarka 11.2014"
    image : "assets/images/issues/112014.jpg"  
  - title : "Eurogospodarka 12.2014"
    image : "assets/images/issues/122014.jpg"
# 2015
  - title : "Eurogospodarka 01.2015"
    image : "assets/images/issues/012015.jpg" 
  - title : "Eurogospodarka 02.2015"
    image : "assets/images/issues/022015.jpg"    
  - title : "Eurogospodarka 03.2015"
    image : "assets/images/issues/032015.jpg"    
  - title : "Eurogospodarka 04.2015"
    image : "assets/images/issues/042015.jpg"
  - title : "Eurogospodarka 05.2015"
    image : "assets/images/issues/052015.jpg"    
  - title : "Eurogospodarka 06.2015"
    image : "assets/images/issues/062015.jpg"   
  - title : "Eurogospodarka 07.2015"
    image : "assets/images/issues/072015.jpg"    
  - title : "Eurogospodarka 08.2015"
    image : "assets/images/issues/082015.jpg"   
  - title : "Eurogospodarka 09.2015"
    image : "assets/images/issues/092015.jpg"   
  - title : "Eurogospodarka 10.2015"
    image : "assets/images/issues/102015.jpg"   
  - title : "Eurogospodarka 11.2015"
    image : "assets/images/issues/112015.jpg"  
  - title : "Eurogospodarka 12.2015"
    image : "assets/images/issues/122015.jpg"
# 2016
  - title : "Eurogospodarka 01.2016"
    image : "assets/images/issues/012016.jpg" 
  - title : "Eurogospodarka 02.2016"
    image : "assets/images/issues/022016.jpg"    
  - title : "Eurogospodarka 03.2016"
    image : "assets/images/issues/032016.jpg"    
  - title : "Eurogospodarka 04.2016"
    image : "assets/images/issues/042016.jpg"
  - title : "Eurogospodarka 05.2016"
    image : "assets/images/issues/052016.jpg"    
  - title : "Eurogospodarka 06.2016"
    image : "assets/images/issues/062016.jpg"   
  - title : "Eurogospodarka 07.2016"
    image : "assets/images/issues/072016.jpg"    
  - title : "Eurogospodarka 08.2016"
    image : "assets/images/issues/082016.jpg"   
  - title : "Eurogospodarka 09.2016"
    image : "assets/images/issues/092016.jpg"   
  - title : "Eurogospodarka 10.2016"
    image : "assets/images/issues/102016.jpg"   
  - title : "Eurogospodarka 11.2016"
    image : "assets/images/issues/112016.jpg"  
# 2019
  - title : "Eurogospodarka 01.2019"
    image : "assets/images/issues/eurogospodarka-01-2019.jpg"
# 2022
  - title : "Eurogospodarka 02.2022"
    image : "assets/images/issues/eurogospodarka-02-2022.jpg"
  - title : "Eurogospodarka 03-04.2022"
    image : "assets/images/issues/eurogospodarka-03-04-2022.jpg"
  - title : "Eurogospodarka 05.2022"
    image : "assets/images/issues/eurogospodarka-5-2022.jpg"
  - title : "Eurogospodarka 06.2022"
    image : "assets/images/issues/eurogospodarka-6-2022.jpg"
  - title : "Eurogospodarka 07.2022"
    image : "assets/images/issues/eurogospodarka-7-2022.jpg"
  - title : "Eurogospodarka 08.2022"
    image : "assets/images/issues/eurogospodarka-8-2022.jpg"
  - title : "Eurogospodarka 09.2022"
    image : "assets/images/issues/eurogospodarka-9-2022.jpg"
  - title : "Eurogospodarka 10.2022"
    image : "assets/images/issues/eurogospodarka-10-2022.jpg"
  - title : "Eurogospodarka 11.2022"
    image : "assets/images/issues/eurogospodarka-11-2022.jpg"
  - title : "Eurogospodarka 12.2022"
    image : "assets/images/issues/eurogospodarka-12-2022.jpg"
# 2023
  - title : "Eurogospodarka 01.2023"
    image : "assets/images/issues/eurogospodarka-1-2023.jpg"
  - title : "Eurogospodarka 02.2023"
    image : "assets/images/issues/eurogospodarka-2-2023.jpg"
  - title : "Eurogospodarka 03.2023"
    image : "assets/images/issues/eurogospodarka-3-2023.jpg"
  - title : "Eurogospodarka 04.2023"
    image : "assets/images/issues/eurogospodarka-4-2023.jpg"
  - title : "Eurogospodarka 05.2023"
    image : "assets/images/issues/eurogospodarka-5-2023.jpg"
  - title : "Eurogospodarka 06.2023"
    image : "assets/images/issues/eurogospodarka-6-2023.jpg"
  - title : "Eurogospodarka 07.2023"
    image : "assets/images/issues/eurogospodarka-7-2023.jpg"
  - title : "Eurogospodarka 08.2023"
    image : "assets/images/issues/eurogospodarka-8-2023.jpg"
  - title : "Eurogospodarka 09.2023"
    image : "assets/images/issues/eurogospodarka-9-2023.jpg"
  - title : "Eurogospodarka 10.2023"
    image : "assets/images/issues/eurogospodarka-10-2023.jpg"
  - title : "Eurogospodarka 11.2023"
    image : "assets/images/issues/eurogospodarka-11-2023.jpg"
  - title : "Eurogospodarka 12.2023"
    image : "assets/images/issues/eurogospodarka-12-2023.jpg"
  - title : "Eurogospodarka 01.2024"
    image : "assets/images/issues/eurogospodarka-01-2024.jpg"
  - title : "Eurogospodarka 02.2024"
    image : "assets/images/issues/eurogospodarka-02-2024.jpg"
  - title : "Eurogospodarka 03.2024"
    image : "assets/images/issues/eurogospodarka-03-2024.jpg"
  - title : "Eurogospodarka 04.2024"
    image : "assets/images/issues/eurogospodarka-04-2024.jpg"
  - title : "Eurogospodarka 05.2024"
    image : "assets/images/issues/eurogospodarka-05-2024.jpg"
  - title : "Eurogospodarka 06.2024"
    image : "assets/images/issues/eurogospodarka-06-2024.jpg"
  - title : "Eurogospodarka 07.2024"
    image : "assets/images/issues/eurogospodarka-07-2024.jpg"
  - title : "Eurogospodarka 08.2024"
    image : "assets/images/issues/eurogospodarka-08-2024.jpg"
  - title : "Eurogospodarka 09.2024"
    image : "assets/images/issues/eurogospodarka-09-2024.jpg"
  - title : "Eurogospodarka 10.2024"
    image : "assets/images/issues/eurogospodarka-10-2024.jpg"

#-------------------------------
# Contact Section

contact-title: Kontakt
contact-email: redakcja@eurogospodarka.eu